[1m========================================================= test session starts =========================================================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0 -- /home/mariana/anaconda3/envs/mlflow-33d7d02cbcccb15d6d2d83802ac3094a9cc7388c/bin/python
cachedir: .pytest_cache
rootdir: /home/mariana/spotify-mlops/check_data
[1mcollected 2 items                                                                                                                     
test_data.py::test_column_presence_and_type <class 'pandas.core.frame.DataFrame'>
[31mFAILED
test_data.py::test_class_names [32mPASSED
============================================================== FAILURES ===============================================================
[31m[1m____________________________________________________ test_column_presence_and_type ____________________________________________________
data =       danceability  energy  loudness  speechiness  acousticness  instrumentalness  liveness  valence  duration_ms genr...    -0.802       0.4290      0.018400          0.024300    0.0778   0.0974       164800  trap
[4461 rows x 10 columns]
    def test_column_presence_and_type(data):
        print(type(data))
        # Disregard the reference dataset
        df = data
        required_columns = {
>           "danceability": pd.api.types.is_float64_dtype,
            "energy": pd.api.types.is_float64_dtype,
            "loudness": pd.api.types.is_float64_dtype,
            "speechiness": pd.api.types.is_float64_dtype,
            "acousticness": pd.api.types.is_float64_dtype,
            "instrumentalness": pd.api.types.is_float64_dtype,
            "liveness": pd.api.types.is_float64_dtype,
            "valence": pd.api.types.is_float64_dtype,
            "duration_ms": pd.api.types.is_int64_dtype,
            "genre": pd.api.types.is_object_dtype,
        }
[31m[1mE       AttributeError: module 'pandas.api.types' has no attribute 'is_float64_dtype'
[31m[1mtest_data.py[39m[22m:11: AttributeError
======================================================= short test summary info =======================================================
FAILED test_data.py::test_column_presence_and_type - AttributeError: module 'pandas.api.types' has no attribute 'is_float64_dtype'
[31m===================================================== [1m1 failed[39m[22m, [32m1 passed[31m in 3.13s =====================================================